### ISSUE TITLE
Load Times

### ISSUE THREAD

**Issue by Blackglade** [discourse/discourse-steam-login#13]
I'm having issues with load times. It seems every time a user signs up, they are never able to actually sign in to steam. it just simply stays at the loading page on the steam website. Never actually fully authenticates.

**Comment by defaye** [comment]
How long has this been an issue?

**Comment by Blackglade** [comment]
Just recent after your latest merge. You can see a picture of it here:

http://puu.sh/tDVQY/049a40dba8.png

The loading never completes...

**Comment by defaye** [comment]
@mrosack can you weigh in on this please. It might have been a mistake on my part to rush through your proposed enhancements, as it seems this may be breaking the authenticator now.

**Comment by mrosack** [comment]
Sorry, I can't duplicate the issue... :( I've been running the newest code on my discourse forum since before the merge, https://discourse.playyourdamnturn.com - could you attempt to sign up there and see if you can duplicate it, @Blackglade?

**Comment by defaye** [comment]
@mrosack seems like it works okay for me :)

**Comment by Blackglade** [comment]
it seems to be working fine on your forum. Must be specific to my installation then. Let me try to figure out what is wrong? (also side note: the username still keeps getting populated as R11 http://puu.sh/tI410/0d1f2345ac.png)

**Comment by mrosack** [comment]
I don't think the domain for the API key matters much.  The R11 thing is weird, but I don't anything that would have caused that in the recent changes. :/  If you want me to try signing up on your discourse I'd be glad to!

**Comment by defaye** [comment]
@Blackglade it is worthwhile changing the API key to something representative of the actual state of your application all the same. Even if it probably doesn't matter

**Comment by Blackglade** [comment]
I ended up figuring it out. It was an issue regarding some serverside caching. I fixed it now. Sorry for the trouble!
