### ISSUE TITLE
Feature: Connection after email auth.

### ISSUE THREAD

**Issue by Technoblazed** [discourse/discourse-steam-login#8]
Allowing clients to connect their steam account after creating an email account?

**Comment by defaye** [comment]
A valid feature. I may put some time aside to look at the current issues with experimental branch as I can't really begin to look at this without some other teething issues being resolved first.

**Comment by Technoblazed** [comment]
np, sorry for the delayed response but thanks :D

**Comment by defaye** [comment]
The plugin will soon be gobbled up by the Discourse team - so I assume this issue will be brought on board by them as well. Sorry that I've not had the time to take a look into this but thanks for the report all the same~

**Comment by erlend-sh** [comment]
\*gobble gobble\* *mmmm, responsibility!*

@defaye thanks for passing the torch! We do hope you'll stick around and contribute as you see fit ❤️

@Technoblazed you should add your support to this overarching request: ["Ability to connect with OAuth providers when user is registered?"](https://meta.discourse.org/t/ability-to-connect-with-oauth-providers-when-user-is-registered/42457?u=erlend_sh)
